export const currencyMap: Record<
  string,
  { countryCode: string; currencyName: string }
> = {
  USD: { countryCode: "US", currencyName: "US Dollar" },
  EUR: { countryCode: "EU", currencyName: "Euro" },
  JPY: { countryCode: "JP", currencyName: "Yen" },
  BGN: { countryCode: "BG", currencyName: "Bulgaria" },
  CZK: { countryCode: "CZ", currencyName: "Czech Republic" },
  GBP: { countryCode: "GB", currencyName: "United Kingdom" },
  BRL: { countryCode: "BR", currencyName: "Brazilian Real" },
  CAD: { countryCode: "CA", currencyName: "Canadian Dollar" },
  AUD: { countryCode: "AU", currencyName: "Australia" },
  DKK: { countryCode: "DK", currencyName: "Danish Krone" },
  HUF: { countryCode: "HU", currencyName: "Hungarian Forint" },
  PLN: { countryCode: "PL", currencyName: "Polish złoty" },
  RON: { countryCode: "RO", currencyName: "Romanian Leu" },
  SEK: { countryCode: "SE", currencyName: "Swedish Krona" },
  CHF: { countryCode: "CH", currencyName: "Swiss Franc" },
  ISK: { countryCode: "IS", currencyName: "Icelandic Króna" },
  NOK: { countryCode: "NO", currencyName: "Norwegian Krone" },
  TRY: { countryCode: "TR", currencyName: "Turkish lira" },
  CNY: { countryCode: "CN", currencyName: "Chinese Yuan" },
  HKD: { countryCode: "HK", currencyName: "Danish Krone" },
  IDR: { countryCode: "ID", currencyName: "Danish Krone" },
  ILS: { countryCode: "IL", currencyName: "Danish Krone" },
  INR: { countryCode: "IN", currencyName: "Danish Krone" },
  KRW: { countryCode: "KR", currencyName: "Danish Krone" },
  MXN: { countryCode: "MX", currencyName: "Danish Krone" },
  MYR: { countryCode: "MY", currencyName: "Danish Krone" },
  NZD: { countryCode: "NZ", currencyName: "Danish Krone" },
  PHP: { countryCode: "PH", currencyName: "Danish Krone" },
  SGD: { countryCode: "SG", currencyName: "Danish Krone" },
  THB: { countryCode: "TH", currencyName: "Danish Krone" },
  ZAR: { countryCode: "ZA", currencyName: "Danish Krone" },
};
